### ISSUE TITLE
Some things to block

### ISSUE THREAD

**Issue by Eyremba** [7rory768/SimpleFreeze#1]
If a player is frozen, this things should be blocked too:

- Bow usage
- Book writing
- Portal usage

Bow usage is maybe blocked by the interact listener, but book writing is maybe possible and the usage of portals could be possible too. (Portal usage is "PlayerPortalEvent")

**Comment by 7rory768** [comment]
Book writing is already on my list and I have just added portal usage per your request, thanks for the suggestion

**Comment by 7rory768** [comment]
Nether/End portal teleportation prevention: b4e797ffd745cae25078291800f50a746d6a0d2b

Bow usage will be blocked in the next commit, will link then.

**Comment by 7rory768** [comment]
Bow prevention: e10ecbea8225e05a65d6ac8e72000ff19ccde08e
