### ISSUE TITLE
Unfreeze disable flying

### ISSUE THREAD

**Issue by schneidermr** [7rory768/SimpleFreeze#2]
After using the unfreeze command the plugin disable flying for the specific player and can not disable this option anywhere.

**Comment by 7rory768** [comment]
If you disable the option that enables fly upon freeze it wont disable fly upon freeze anymore
https://github.com/7rory768/SimpleFreeze/blob/master/resources/config.yml#L112

**Comment by schneidermr** [comment]
I've tried it but doesn't help anything. After I use the unfreeze command the player can't fly anymore. (I use Spigot 1.11.2 and in server.properties allow-flight is true and in essentials config send-fly-enable-on-join is also true. But the player doesn't have permission to use the fly command.)

Can you look at these lines? https://github.com/7rory768/SimpleFreeze/blob/master/src/org/plugins/simplefreeze/managers/FreezeManager.java#L66-L67

**Comment by 7rory768** [comment]
oh you'e right, I'll push an update soon

**Comment by schneidermr** [comment]
Can you please update the plugin or explain how to build a fixed version from the source? Is it a Maven project and you ignore some files/folders or you use an other solution for build?

**Comment by 7rory768** [comment]
I don't use maven at all but don't worry I'll do it when i get back from vacation in a little over a week. Sorry that I didn't do it before I left, honestly Iforgot

**Comment by schneidermr** [comment]
Can you fix this bug?

**Comment by 7rory768** [comment]
Fixed, will be released in 3.1.1

**Comment by schneidermr** [comment]
Thank you
