### ISSUE TITLE
GUI closing before it's able to be viewed.

### ISSUE THREAD

**Issue by IgnitingIce** [7rory768/SimpleFreeze#3]
In my config, I've got the 'allow-close' in the gui section set to true, as I just want it as a 1 time popup when a player is first frozen, however I also have a default location set and if the player is teleported to that location without having the chunks already loaded, the gui pops up the closes itself almost instantly. When I change allow-close to false, it stays open of course, but I'd rather not force the player to have to close the game if they wish to leave. To be clear, if the player is already near where the default location they are sent to is and already have the chunks loaded, the gui pops up and is only closed when the player closes it, but if the player is anywhere else, not near the location they get sent to, the gui pops up, but closes itself a split second later. Maybe a brief delay on opening the gui after a player is teleported would fix this? There are no console errors or anything of the sort.

**Comment by 7rory768** [comment]
Try 3.1.1 and lmk if the problem still persists, I added a 5tick delay https://github.com/7rory768/SimpleFreeze/commit/99adf2c26f6f13a52f1dc02f492ffe4da5735ef5

**Comment by IgnitingIce** [comment]
Doesn't seem to have fixed it. Is there anything I can do, or info I can give that might help you troubleshoot?

**Comment by 7rory768** [comment]
Try this and let me know if it fixes, its a 1 second delay now
https://drive.google.com/file/d/0Bw2H-Kh-6UvdcEtCZ1U3SF9welU/view?usp=sharing

**Comment by IgnitingIce** [comment]
The longer delay seems to have fixed it, thanks for the help!
